import {
  DisplayHeadingMainFontFamily,
  DisplayHeadingMainFontWeight,
  DisplayHeadingMainLineHeight,
  DisplayHeadingMainFontSize,
  DisplayHeadingMainLetterSpacing,
  DisplayHeadingMainTextDecoration,
  DisplayHeadingMainTextCase,
  H1HeadingMainFontFamily,
  H1HeadingMainFontWeight,
  H1HeadingMainLineHeight,
  H1HeadingMainFontSize,
  H1HeadingMainLetterSpacing,
  H1HeadingMainTextDecoration,
  H1HeadingMainTextCase,
  H2HeadingMainFontFamily,
  H2HeadingMainFontWeight,
  H2HeadingMainLineHeight,
  H2HeadingMainFontSize,
  H2HeadingMainLetterSpacing,
  H2HeadingMainTextDecoration,
  H2HeadingMainTextCase,
  H3HeadingMainFontFamily,
  H3HeadingMainFontWeight,
  H3HeadingMainLineHeight,
  H3HeadingMainFontSize,
  H3HeadingMainLetterSpacing,
  H3HeadingMainTextDecoration,
  H3HeadingMainTextCase,
  BodyFontFamily,
  BodyFontWeight,
  BodyFontSize,
  BodyLetterSpacing,
  BodyTextCase,
  NoteFontFamily,
  NoteFontWeight,
  NoteFontSize,
  NoteLetterSpacing,
  H4HeadingMainFontFamily,
  H4HeadingMainFontSize,
  H4HeadingMainFontWeight,
  H4HeadingMainLetterSpacing,
  H4HeadingMainLineHeight,
  H4HeadingMainTextDecoration,
} from "../../../../tokens/js/variables";

const styles: Record<string, React.CSSProperties> = {
  display: {
    margin: 0,
    padding: 0,
    fontFamily: DisplayHeadingMainFontFamily,
    fontWeight: DisplayHeadingMainFontWeight,
    lineHeight: DisplayHeadingMainLineHeight,
    fontSize: DisplayHeadingMainFontSize,
    letterSpacing: DisplayHeadingMainLetterSpacing,
    textDecoration: DisplayHeadingMainTextDecoration,
    textTransform:
      DisplayHeadingMainTextCase as React.CSSProperties["textTransform"],
  },
  h1: {
    margin: 0,
    fontFamily: H1HeadingMainFontFamily,
    fontWeight: H1HeadingMainFontWeight,
    lineHeight: H1HeadingMainLineHeight,
    fontSize: H1HeadingMainFontSize,
    letterSpacing: H1HeadingMainLetterSpacing,
    textDecoration: H1HeadingMainTextDecoration,
    textTransform:
      H1HeadingMainTextCase as React.CSSProperties["textTransform"],
  },
  h2: {
    margin: 0,
    fontFamily: H2HeadingMainFontFamily,
    fontWeight: H2HeadingMainFontWeight,
    lineHeight: H2HeadingMainLineHeight,
    fontSize: H2HeadingMainFontSize,
    letterSpacing: H2HeadingMainLetterSpacing,
    textDecoration: H2HeadingMainTextDecoration,
    textTransform:
      H2HeadingMainTextCase as React.CSSProperties["textTransform"],
  },
  h3: {
    margin: 0,
    fontFamily: H3HeadingMainFontFamily,
    fontWeight: H3HeadingMainFontWeight,
    lineHeight: H3HeadingMainLineHeight,
    fontSize: H3HeadingMainFontSize,
    letterSpacing: H3HeadingMainLetterSpacing,
    textDecoration: H3HeadingMainTextDecoration,
    textTransform:
      H3HeadingMainTextCase as React.CSSProperties["textTransform"],
  },
  h4: {
    margin: 0,
    fontFamily: H4HeadingMainFontFamily,
    fontWeight: H4HeadingMainFontWeight,
    lineHeight: H4HeadingMainLineHeight,
    fontSize: H4HeadingMainFontSize,
    letterSpacing: H4HeadingMainLetterSpacing,
    textDecoration: H4HeadingMainTextDecoration,
    textTransform:
      H3HeadingMainTextCase as React.CSSProperties["textTransform"],
  },
  body: {
    margin: 0,
    fontFamily: BodyFontFamily,
    fontWeight: BodyFontWeight,
    fontSize: BodyFontSize,
    letterSpacing: BodyLetterSpacing,
  },
  note: {
    margin: 0,
    fontFamily: NoteFontFamily,
    fontWeight: NoteFontWeight,
    fontSize: NoteFontSize,
    letterSpacing: NoteLetterSpacing,
    textTransform: BodyTextCase as React.CSSProperties["textTransform"],
  },
};

export default styles;
